version: "3.8"

services:
  postgres:
    container_name: "postgres_datasource_cryptochat"
    image: postgres:15.1
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: itmoitmo
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"